### PR TITLE
#207: Fix replication scorepayload error

### LINKED ISSUE #207: Error in Schema Validation
Running schema validation in Certification Utils sometimes throws an error on line 384 of `/lib/replication/utils`:

Currently, the code is similar to the following:

`} else if (fieldDataType !== 'Edm.String' && value?.includes(',')) {`

However, if value doesn't exist or it doesn't have an `includes` function (i.e. not a string) then it will throw an error.

The following change seems to fix it, but we need to double-check that it doesn't have an unintended side effects:

`} else if (fieldDataType !== 'Edm.String' && value && value?.includes && value?.includes(',')) {`


The original stack trace was:

```
Schema validation errors found in the Property payload!                                                                                                                                                                                                                                                                                                                                                                                
TypeError: value?.includes is not a function                                                                                                                                                                                                                                                                                                                                                                                           
    at /lib/replication/utils.js:384:67                                                                                                                                                                            
    at Array.forEach (<anonymous>)                                                                                                                                                                                 
    at /lib/replication/utils.js:332:42                                                                                                                                                                            
    at Array.forEach (<anonymous>)                                                                                                                                                                                                                                                                                                                                                                                                     
    at /lib/replication/utils.js:314:7                                                                                                                                                                                                                                                                                                                                                                                                 
    at Array.forEach (<anonymous>)                                                                                                                                                                                 
    at scorePayload (/lib/replication/utils.js:310:11)                                                                                                                                                             
    at replicate (/lib/replication/index.js:228:17)                                                                                                                                                                
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
```

### PR DESCRIPTION
**Pull request by mohit-s96**
closes #207

### CODE REVIEW

File: lib/replication/utils.js [hunk 1]
```diff
@@ -381,7 +381,7 @@ const scorePayload = ({
                 // arrays are for collections of string or Edm.EnumType enumerations
                 // which can be processed as-is
                 value.forEach(lookupValue => incrementLookupValueFrequency({ availabilityMap, fieldName, lookupValue }));
-              } else if (fieldDataType !== 'Edm.String' && value?.includes(',')) {
+              } else if (fieldDataType !== 'Edm.String' && typeof value === 'string' && value?.includes(',')) {
```
Comment (darnjo) [inline lib/replication/utils.js:384]: This won't handle the case where value is null or undefined?

**Review by darnjo — CHANGES_REQUESTED** [review]

**Review by darnjo — APPROVED** [review]
