### PR TITLE
#118: Schema validation issues for enumerations

### LINKED ISSUE #118: Schema Validation issues for Enumerations
There have been some reports of cases where an enumerated value with commas is being interpreted as two separate values rather than a single value.

For example, "My Company, LLC." throws an error that both "My Company" and " LLC." are not present in the metadata so schema validation fails.

The first step is that tests should be written for this case to ensure it doesn't regress in the future.

### PR DESCRIPTION
**Pull request by mohit-s96**
closes #118

### CODE REVIEW

File: lib/schema/validate.js [hunk 1]
```diff
@@ -17,6 +17,27 @@ const buildEnumMap = (enums = []) =>
     return acc;
   }, {});
 
+const resolveStringList = (string, enums) => {
+  // Quick check if the entire string is a valid enum, return it as an array
+  if (enums.includes(string)) return [string];
+
+  // Split the string on commas not followed by a space
```
Comment (darnjo) [inline lib/schema/validate.js:24]: This need to do resolution by types instead. 

* If the underlying type for the enumeration is Edm.String, then it's a string value and should not be split.
* If it's anything else, it should be split on commas and treated as a list, if that's what it is.

**Review by darnjo — CHANGES_REQUESTED** [review]

**Review by darnjo — COMMENTED** [review]
Looks good. Thanks. 👍

**Review by darnjo — APPROVED** [review]
